# The URL the site will be built for
base_url = "https://malramsay.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "inspired-github"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "tale-zola"

title="Malcolm Ramsay"
generate_feed=true

taxonomies = [
    { name = "tags" },
]

[extra]
# Put all your custom variables here
author = "Malcolm Ramsay"
github = "https://github.com/malramsay64"
email  = "m@malramsay.com"

timeformat = "%Y-%m-%d"

menu = [
{ name = "Home", url = "/" },
{ name = "Blog", url = "/post/" },
{ name = "Talks", url = "/talks/" },
{ name = "Projects", url = "/projects/" },
# { name = "Publications", url = "/publication/" },
]

[extra.footer]
start_year = "2017"  # start year of the site
end_year = "2021"    # end year of the site
info = ""

